### ISSUE TITLE
Promoting to king does not mark the piece as king

### ISSUE THREAD

**Issue by campovski** [RoepStoep/lidraughts#3]
I believe that this happens when you **promote after the capturing sequence**, although I am only 99% sure that is true.

Here is the [screenshot](https://imgur.com/a/PhO1eGr) of the game, white has promoted and his last move was king move. Even after move the piece still remained not marked as king.

**Comment by RoepStoep** [comment]
You're right, it only fails when promoting from a capture. But we're quite lucky you discovered this bug so early, because this only happens when there's at the same time another capture on the board with at least a length of 2, as in your game: https://lidraughts.org/UJbtytFE/black#76

Thanks for reporting!
